---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: fluentd
subjects:
- kind: ServiceAccount
  name: fluentd
  namespace: sumologic
roleRef:
  kind: ClusterRole
  name: fluentd
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: fluentd
  labels:
    k8s-app: fluentd-sumologic
rules:
- apiGroups: [""]
  resources:
  - configmaps
  - namespaces
  - nodes
  - pods
  - services
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps", "extensions"]
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs: ["get", "list", "watch"]
- apiGroups: ["events.k8s.io"]
  resources:
  - events
  verbs: ["get", "list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd
  namespace: sumologic
  labels:
    k8s-app: fluentd-sumologic
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: sumologic
data:
  fluent.conf: |-
    @include metrics.conf
    @include events.conf
    @include logs.conf
  metrics.conf: |-
    <source>
      @type http
      port 9888
      <parse>
        @type protobuf
      </parse>
    </source>
    <match prometheus.metrics.operator.rule>
      @type datapoint
      tag prometheus.datapoint.operator.rule
    </match>
    <match prometheus.metrics**>
      @type datapoint
      tag prometheus.datapoint
    </match>
    <match prometheus.datapoint>
      @type rewrite_tag_filter
      <rule>
        key job
        pattern ^(.*)$
        tag ${tag}.$1
      </rule>
    </match>
    <filter prometheus.datapoint**>
      @type enhance_k8s_metadata
    </filter>
    <filter prometheus.datapoint**>
      @type prometheus_format
      relabel container_name:container,pod_name:pod
    </filter>
    <match prometheus.datapoint.apiserver**>
      @type sumologic
      endpoint "#{ENV['SUMO_ENDPOINT_METRICS_APISERVER']}"
      data_type metrics
      metric_data_format prometheus
      disable_cookies true
    </match>
    <match prometheus.datapoint.kubelet**>
      @type sumologic
      endpoint "#{ENV['SUMO_ENDPOINT_METRICS_KUBELET']}"
      data_type metrics
      metric_data_format prometheus
      disable_cookies true
    </match>
    <match prometheus.datapoint.kube-controller-manager**>
      @type sumologic
      endpoint "#{ENV['SUMO_ENDPOINT_METRICS_KUBE_CONTROLLER_MANAGER']}"
      data_type metrics
      metric_data_format prometheus
      disable_cookies true
    </match>
    <match prometheus.datapoint.kube-scheduler**>
      @type sumologic
      endpoint "#{ENV['SUMO_ENDPOINT_METRICS_KUBE_SCHEDULER']}"
      data_type metrics
      metric_data_format prometheus
      disable_cookies true
    </match>
    <match prometheus.datapoint.kube-state**>
      @type sumologic
      endpoint "#{ENV['SUMO_ENDPOINT_METRICS_KUBE_STATE']}"
      data_type metrics
      metric_data_format prometheus
      disable_cookies true
    </match>
    <match prometheus.datapoint.node-exporter**>
      @type sumologic
      endpoint "#{ENV['SUMO_ENDPOINT_METRICS_NODE_EXPORTER']}"
      data_type metrics
      metric_data_format prometheus
      disable_cookies true
    </match>
    <match prometheus.datapoint**>
      @type sumologic
      endpoint "#{ENV['SUMO_ENDPOINT_METRICS']}"
      data_type metrics
      metric_data_format prometheus
      disable_cookies true
    </match>
  events.conf: |-
    <source>
      @type dummy
      tag "dummy.events"
      dummy {"hello":"world"}
    </source>
    <match "dummy.events">
      @type null
    </match>
  logs.conf: |-
    <source>
      @type dummy
      tag "dummy.logs"
      dummy {"hello":"world"}
    </source>
    <match "dummy.logs">
      @type null
    </match>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd
  namespace: sumologic
  labels:
    k8s-app: fluentd-sumologic
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-sumologic
  replicas: 3
  template:
    metadata:
      labels:
        k8s-app: fluentd-sumologic
    spec:
      serviceAccountName: fluentd
      volumes:
      - name: pos-files
        hostPath:
          path: /var/run/fluentd-pos
          type: ""
      - name: config-volume
        configMap:
          name: fluentd-config
      containers:
      - name: fluentd
        image: byisumo/kubernetes-fluentd
        imagePullPolicy: Always
        resources:
          limits:
            memory: 256Mi
            cpu: "100m"
          requests:
            memory: 256Mi
            cpu: "100m"
        ports:
        - name: prom-write
          containerPort: 9888
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - "/bin/sh"
            - "-c"
            - "[[ $( pgrep ruby | wc -l)  == 2 ]]"
          initialDelaySeconds: 300
          periodSeconds: 20
        readinessProbe:
          exec:
            command:
            - "/bin/sh"
            - "-c"
            - "[[ $( pgrep ruby | wc -l)  == 2 ]]"
          initialDelaySeconds: 45
          periodSeconds: 5
        volumeMounts:
        - name: config-volume
          mountPath: /fluentd/etc/
        - name: pos-files
          mountPath: /mnt/pos/
        env:
        - name: SUMO_ENDPOINT_METRICS
          valueFrom:
            secretKeyRef:
              name: metric-endpoints
              key: endpoint-metrics
        - name: SUMO_ENDPOINT_METRICS_APISERVER
          valueFrom:
            secretKeyRef:
              name: metric-endpoints
              key: endpoint-metrics-apiserver
        - name: SUMO_ENDPOINT_METRICS_KUBELET
          valueFrom:
            secretKeyRef:
              name: metric-endpoints
              key: endpoint-metrics-kubelet
        - name: SUMO_ENDPOINT_METRICS_KUBE_CONTROLLER_MANAGER
          valueFrom:
            secretKeyRef:
              name: metric-endpoints
              key: endpoint-metrics-kube-controller-manager
        - name: SUMO_ENDPOINT_METRICS_KUBE_SCHEDULER
          valueFrom:
            secretKeyRef:
              name: metric-endpoints
              key: endpoint-metrics-kube-scheduler
        - name: SUMO_ENDPOINT_METRICS_KUBE_STATE
          valueFrom:
            secretKeyRef:
              name: metric-endpoints
              key: endpoint-metrics-kube-state
        - name: SUMO_ENDPOINT_METRICS_NODE_EXPORTER
          valueFrom:
            secretKeyRef:
              name: metric-endpoints
              key: endpoint-metrics-node-exporter
---
apiVersion: v1
kind: Service
metadata:
  name: fluentd
  namespace: sumologic
  labels:
    k8s-app: fluentd-sumologic
spec:
  selector:
    k8s-app: fluentd-sumologic
  ports:
  - name: prom-write
    port: 9888
    targetPort: 9888
    protocol: TCP
---
